// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetUserByPhone(ctx context.Context, phoneNumber string) (User, error)
	UpdateUserOTP(ctx context.Context, arg UpdateUserOTPParams) (User, error)
}

var _ Querier = (*Queries)(nil)
